# Generated by Django 5.1.1 on 2024-10-10 05:04

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="principaldesk",
            name="published_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="principaldesk",
            name="title",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
