# Generated by Django 5.1.3 on 2024-11-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
