# Generated by Django 5.1.3 on 2024-11-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_marks_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicforonlinetest',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tradeforonlinetest',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
