# Generated by Django 5.1.1 on 2024-10-10 05:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_principaldesk_published_date_principaldesk_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="principaldesk",
            name="published_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
