# Generated by Django 5.1.1 on 2024-10-10 05:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_alter_principaldesk_published_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsalert",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="attachments/"),
        ),
        migrations.AlterField(
            model_name="newsalert",
            name="published_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
