# Generated by Django 5.1.3 on 2024-11-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_tender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='attachment',
            field=models.FileField(blank=True, upload_to='tenders/'),
        ),
    ]
