# Generated by Django 5.1.3 on 2024-11-29 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_tender_attachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tender',
        ),
    ]
