# Generated by Django 5.1.3 on 2024-11-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_delete_tender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particulars', models.CharField(max_length=255)),
                ('attachment', models.FileField(upload_to='tenders/')),
                ('status', models.CharField(choices=[('Open Soon', 'Open Soon'), ('Upcoming', 'Upcoming'), ('Opened', 'Opened'), ('Closed', 'Closed'), ('Re-Open', 'Re-Open'), ('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Awarded', 'Awarded')], default='Upcoming', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
