# Generated by Django 5.1.2 on 2024-10-11 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_adminstaff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminstaff',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='adminstaff',
            name='remarks',
        ),
    ]
