# Generated by Django 5.1.3 on 2024-11-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_tender_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='status',
            field=models.CharField(choices=[('Open Soon', 'Open Soon'), ('Upcoming', 'Upcoming'), ('Opened', 'Opened'), ('Closed', 'Closed'), ('Re Open', 'Re Open'), ('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Awarded', 'Awarded')], default='Upcoming', max_length=20),
        ),
    ]
