# Generated by Django 5.1.2 on 2024-10-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_mymodel_techstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='images/default_logo.png', upload_to='images/')),
                ('h1_text', models.CharField(default='GOVT INDUSTRIAL TRAINING INSTITUTE', max_length=255)),
                ('h2_text', models.CharField(default='Krishangarh (Kuthar) H.P.', max_length=255)),
                ('p_text', models.TextField(default='DEPARTMENT OF TECHNICAL EDUCATION, VOCATIONAL & INDUSTRIAL TRAINING (H.P.)')),
                ('p_address', models.TextField(default='Govt. Industrial Training Institute Krishangarh, Tehsil Kuthar Distt. Solan (HP)')),
                ('contact_info', models.CharField(default='Phone No: 01792-200000 Email Id: itikuthar22@gmail.com', max_length=255)),
                ('login_button_text', models.CharField(default='Login Admin', max_length=50)),
                ('admission_button_text', models.CharField(default='Admission', max_length=50)),
            ],
        ),
    ]
