# Generated by Django 5.1.2 on 2024-10-13 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_headercontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeaderContent',
        ),
    ]
