# Generated by Django 5.1.2 on 2024-10-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_headercontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headercontent',
            name='email',
        ),
        migrations.RemoveField(
            model_name='headercontent',
            name='phone',
        ),
        migrations.AddField(
            model_name='headercontent',
            name='admin_button_link',
            field=models.URLField(default='http://127.0.0.1:8000/admin/'),
        ),
        migrations.AddField(
            model_name='headercontent',
            name='admin_button_text',
            field=models.CharField(default='Login Admin', max_length=50),
        ),
        migrations.AddField(
            model_name='headercontent',
            name='admission_button_link',
            field=models.URLField(default='/admission/'),
        ),
        migrations.AddField(
            model_name='headercontent',
            name='admission_button_text',
            field=models.CharField(default='Admission', max_length=50),
        ),
        migrations.AddField(
            model_name='headercontent',
            name='contact_details',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headercontent',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
