# Generated by Django 5.1.2 on 2024-10-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_headercontent_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headercontent',
            name='address',
        ),
        migrations.RemoveField(
            model_name='headercontent',
            name='contact_details',
        ),
        migrations.RemoveField(
            model_name='headercontent',
            name='department',
        ),
        migrations.RemoveField(
            model_name='headercontent',
            name='institute_name',
        ),
        migrations.RemoveField(
            model_name='headercontent',
            name='institute_subtitle',
        ),
        migrations.RemoveField(
            model_name='headercontent',
            name='logo',
        ),
        migrations.AddField(
            model_name='headercontent',
            name='donation_button_link',
            field=models.URLField(default='/donation/'),
        ),
        migrations.AddField(
            model_name='headercontent',
            name='donation_button_text',
            field=models.CharField(default='Donate Now', max_length=50),
        ),
    ]
