# Generated by Django 5.1.2 on 2024-10-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_remove_headercontent_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headercontent',
            name='address',
            field=models.TextField(default='Govt. Industrial Training Institute Krishangarh, Tehsil Kuthar Distt. Solan (HP)'),
        ),
        migrations.AddField(
            model_name='headercontent',
            name='department',
            field=models.CharField(default='DEPARTMENT OF TECHNICAL EDUCATION, VOCATIONAL & INDUSTRIAL TRAINING (H.P.)', max_length=255),
        ),
        migrations.AddField(
            model_name='headercontent',
            name='email',
            field=models.EmailField(default='itikuthar22@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='headercontent',
            name='institute_name',
            field=models.CharField(default='GOVT INDUSTRIAL TRAINING INSTITUTE', max_length=255),
        ),
        migrations.AddField(
            model_name='headercontent',
            name='institute_subtitle',
            field=models.CharField(default='Krishangarh (Kuthar) H.P.', max_length=255),
        ),
        migrations.AddField(
            model_name='headercontent',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='headercontent',
            name='phone',
            field=models.CharField(default='01792-284531', max_length=20),
        ),
    ]
