# Generated by Django 5.1.2 on 2024-10-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_headercontent_address_headercontent_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headercontent',
            name='admission_button_link',
            field=models.CharField(default='/admission/', max_length=200),
        ),
        migrations.AlterField(
            model_name='headercontent',
            name='donation_button_link',
            field=models.CharField(default='/donation/', max_length=200),
        ),
    ]
