# Generated by Django 5.1.2 on 2024-10-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_headercontent_admission_button_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('paragraph1', models.TextField()),
                ('paragraph2', models.TextField()),
                ('paragraph3', models.TextField()),
                ('button1_text', models.CharField(max_length=255)),
                ('button1_url', models.CharField(max_length=255)),
                ('button2_text', models.CharField(max_length=255)),
                ('button2_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='HeaderContent',
        ),
    ]
