# Generated by Django 5.1.2 on 2024-10-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_header_delete_headercontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logos/')),
                ('h1', models.CharField(max_length=200)),
                ('h2', models.CharField(max_length=200)),
                ('paragraph1', models.TextField()),
                ('paragraph2', models.TextField()),
                ('paragraph3', models.TextField()),
                ('button1_text', models.CharField(max_length=100)),
                ('button1_url', models.CharField(max_length=200)),
                ('button2_text', models.CharField(max_length=100)),
                ('button2_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Header',
        ),
    ]
