# Generated by Django 5.1.2 on 2024-10-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0018_headercontent_delete_header"),
    ]

    operations = [
        migrations.AddField(
            model_name="principaldesk",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="principal_images/"
            ),
        ),
    ]
