# Generated by Django 5.1.2 on 2024-10-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0019_principaldesk_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="SliderImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="slider_images/")),
                ("caption", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
